version: '3.7'

services:
  api:
    build:
      context: .
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  node_modules:
    driver: local
  pg_data:
    driver: local
